# Site settings
#博客名称
name: Pabebe Blog
#邮箱
email: zezuwang@qq.com
#作者
author: Pabebe
#个人网站
url: https://github.com/Pabebezz/blog.io
#个人简历网站
resume_site: https://github.com/Pabebezz/
#gitHub网址
github_username: Pabebezz
github: https://github.com/Pabebezz/
baseurl: ""
#博客相关描述
description: Actually, less is more!
meta_description: 业精于勤，慌于嬉；行成于思，毁于随
motto: I have soulful eyes of a cow.
banner: 业精于勤，慌于嬉；行成于思，毁于随

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']


# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

