# Site settings
name: Pabebe
email: zezuwang@qq.com
author: Pabebe
url: https://github.com/Pabebezz/pabebe.github.io
resume_site: https://github.com/Pabebezz/
github: https://github.com/Pabebezz/
baseurl: ""
description: Actually, less is more!
meta_description: 业精于勤，慌于嬉；行成于思，毁于随
motto: It's our wits that make us men.
banner: 业精于勤，慌于嬉；行成于思，毁于随

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: Pabebezz

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

